# Generated by Django 3.2.9 on 2021-11-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionals',
            name='zip_code',
            field=models.CharField(max_length=8),
        ),
    ]
