# Generated by Django 3.2.9 on 2021-11-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0003_alter_professionals_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionals',
            name='city',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
